name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this based on your project's Node.js version

    - name: Install dependencies
      run: npm install  # If your project requires it

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
